import type { Metadata } from "next";
import localFont from "next/font/local";

import { Fjalla_One, Allura } from 'next/font/google';

const itc_benguiat = localFont({
    src: "./fonts/itcbenguiatstdbookcn-webfont.woff",
    variable: '--font-itc_benguiat',
    weight: "400",
});

const fjalla_one = Fjalla_One({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-fjalla-one',
    display: 'swap',
})

const allura = Allura({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-allura',
    display: 'swap',
})

import "./globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${itc_benguiat.variable} ${fjalla_one.variable} ${allura.variable}`}>
            <body>
                {children}
            </body>
        </html>
    );
}
